### PR TITLE
fix(w3c): remove revisionTypes config, use querySelector instead

### LINKED ISSUE #4735: Remove revisionTypes
## Description of problem

The revisionTypes conflig doesn’t follow Respec conventions? Need to check where it came from. The content of that should be derived automatically and added to the SoTD. 

Generally, if it’s a updatable rec, and it has corrections or additions, add the appropriate content. It shouldn’t use a configuration option.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #4735

### CODE REVIEW

**Review by sidvishnoi — APPROVED** [review]

**Comment by sidvishnoi** [comment]
Might need to update specs using above config option?

**Comment by marcoscaceres** [comment]
Will look for them now... 

* [w3c/webrtc-pc](https://github.com/w3c/webrtc-pc)
* [w3c/html-aria](https://github.com/w3c/html-aria)
* [w3c/geolocation](https://github.com/w3c/geolocation)

Will send PRs.

**Comment by marcoscaceres** [comment]
@sidvishnoi, can you ping me after you do a release? I'll do them then.

**Comment by sidvishnoi** [comment]
@marcoscaceres Released.

**Pull request merged**
